-- MySQL Script generated by MySQL Workbench
-- Wed Jul 26 15:53:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema glastopf
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `glastopf` ;

-- -----------------------------------------------------
-- Schema glastopf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `glastopf` DEFAULT CHARACTER SET utf8 ;
USE `glastopf` ;

-- -----------------------------------------------------
-- Table `glastopf`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`table1` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`table1` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT NULL,
  `firsttime` VARCHAR(45) NULL,
  `lasttime` VARCHAR(45) NULL,
  PRIMARY KEY (`content`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glastopf`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`events` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(45) NULL,
  `source` VARCHAR(45) NULL,
  `request_url` VARCHAR(1000) NULL,
  `request_raw` LONGTEXT NULL,
  `pattern` VARCHAR(45) NULL,
  `filename` VARCHAR(1000) NULL,
  `version` VARCHAR(45) NULL,
  `sensorid` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glastopf`.`ext`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`ext` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`ext` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT NULL,
  `firsttime` VARCHAR(45) NULL,
  `lasttime` VARCHAR(45) NULL,
  PRIMARY KEY (`content`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glastopf`.`filetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`filetype` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`filetype` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT NULL,
  `firsttime` VARCHAR(45) NULL,
  `lasttime` VARCHAR(45) NULL,
  PRIMARY KEY (`content`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glastopf`.`intext`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`intext` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`intext` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT NULL,
  `firsttime` VARCHAR(45) NULL,
  `lasttime` VARCHAR(45) NULL,
  PRIMARY KEY (`content`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glastopf`.`intitle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`intitle` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`intitle` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT NULL,
  `firsttime` VARCHAR(45) NULL,
  `lasttime` VARCHAR(45) NULL,
  PRIMARY KEY (`content`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glastopf`.`inurl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`inurl` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`inurl` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT NULL,
  `firsttime` VARCHAR(45) NULL,
  `lasttime` VARCHAR(45) NULL,
  PRIMARY KEY (`content`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glastopf`.`ip_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`ip_profiles` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`ip_profiles` (
  `ip` VARCHAR(15) NOT NULL,
  `as_number` VARCHAR(10) NULL,
  `as_name` VARCHAR(120) NULL,
  `country_code` VARCHAR(10) NULL,
  `total_requests` INT NULL,
  `total_scans` INT NULL,
  `bgp_prefix` VARCHAR(100) NULL,
  `requests_per_scan` FLOAT NULL,
  `avg_scan_duration` FLOAT NULL,
  `scan_time_period` FLOAT NULL,
  `last_event_time` VARCHAR(30) NULL,
  `comments` LONGTEXT NULL,
  PRIMARY KEY (`ip`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
