-- MySQL Script generated by MySQL Workbench
-- Wed Jul 26 15:45:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Honeypot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Honeypot` ;

-- -----------------------------------------------------
-- Schema Honeypot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Honeypot` DEFAULT CHARACTER SET utf8 ;
USE `Honeypot` ;

-- -----------------------------------------------------
-- Table `Honeypot`.`Cowrie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Honeypot`.`Cowrie` ;

CREATE TABLE IF NOT EXISTS `Honeypot`.`Cowrie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `session` VARCHAR(45) NULL DEFAULT NULL,
  `eventid` VARCHAR(45) NULL DEFAULT NULL,
  `timestamp` VARCHAR(45) NULL DEFAULT NULL,
  `message` VARCHAR(1000) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `system` VARCHAR(45) NULL DEFAULT NULL,
  `src_ip` VARCHAR(45) NULL DEFAULT NULL,
  `src_port` INT(11) NULL DEFAULT NULL,
  `dst_ip` VARCHAR(45) NULL DEFAULT NULL,
  `dst_port` INT(11) NULL DEFAULT NULL,
  `input` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `session_in` (`session` ASC),
  INDEX `eventid_in` (`eventid` ASC),
  INDEX `timestamp_in` (`timestamp` ASC),
  INDEX `message_in` (`message` ASC),
  INDEX `username_in` (`username` ASC),
  INDEX `password_in` (`password` ASC),
  INDEX `system_in` (`system` ASC),
  INDEX `src_ip_in` (`src_ip` ASC),
  INDEX `src_port_in` (`src_port` ASC),
  INDEX `dst_ip_in` (`dst_ip` ASC),
  INDEX `dst_port_in` (`dst_port` ASC),
  INDEX `input` (`input` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 29644
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Honeypot`.`Honeytrap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Honeypot`.`Honeytrap` ;

CREATE TABLE IF NOT EXISTS `Honeypot`.`Honeytrap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_virtual` VARCHAR(45) NULL,
  `timestamp` VARCHAR(45) NULL,
  `start_time` VARCHAR(45) NULL,
  `end_time` VARCHAR(45) NULL,
  `attack_protocol` VARCHAR(45) NULL,
  `remote_ip` VARCHAR(45) NULL,
  `remote_port` INT NULL,
  `local_ip` VARCHAR(45) NULL,
  `local_port` INT NULL,
  `payload_md5` VARCHAR(45) NULL,
  `payload_sha512` VARCHAR(100) NULL,
  `payload_len` INT NULL,
  `payload_datahex` LONGTEXT NULL,
  `proxy_protocol` VARCHAR(45) NULL,
  `proxy_rmip` VARCHAR(45) NULL,
  `proxy_rmport` INT NULL,
  `proxy_loip` VARCHAR(45) NULL,
  `proxy_loport` INT NULL,
  `proxy_payload_md5` VARCHAR(45) NULL,
  `proxy_payload_sha512` VARCHAR(100) NULL,
  `proxy_payload_len` INT NULL,
  `proxy_payload_datahex` LONGTEXT NULL,
  `operation_mode` INT NULL,
  `download_count` INT NULL,
  `download_tries` INT NULL,
  `downloads` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_idx` (`id` ASC),
  INDEX `timestamp_idx` (`timestamp` ASC),
  INDEX `start_time_idx` (`start_time` ASC),
  INDEX `end_time_idx` (`end_time` ASC),
  INDEX `attack_protocol_idx` (`attack_protocol` ASC),
  INDEX `remoteip_idx` (`remote_ip` ASC),
  INDEX `remote_port_idx` (`remote_port` ASC),
  INDEX `local_ip_idx` (`local_ip` ASC),
  INDEX `local_port_idx` (`local_port` ASC),
  INDEX `payload_md5_idx` (`payload_md5` ASC),
  INDEX `payload_md512_idx` (`payload_sha512` ASC),
  INDEX `payload_len_idx` (`payload_len` ASC),
  INDEX `proxy_protocol_idx` (`proxy_protocol` ASC),
  INDEX `proxy_rmip_idx` (`proxy_rmip` ASC),
  INDEX `proxy_rmport_idx` (`proxy_rmport` ASC),
  INDEX `proxy_loip_idx` (`proxy_loip` ASC),
  INDEX `proxy_loport_idx` (`proxy_loport` ASC),
  INDEX `proxy_payload_md5_idx` (`proxy_payload_md5` ASC),
  INDEX `proxy_payload_md512_idx` (`proxy_payload_sha512` ASC),
  INDEX `proxy_payload_len_idx` (`proxy_payload_len` ASC),
  INDEX `operation_mode_idx` (`operation_mode` ASC),
  INDEX `download_count_idx` (`download_count` ASC),
  INDEX `download_tries_idx` (`download_tries` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Honeypot`.`Conpot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Honeypot`.`Conpot` ;

CREATE TABLE IF NOT EXISTS `Honeypot`.`Conpot` (
  `timestamp` VARCHAR(45) NOT NULL,
  `src_ip` VARCHAR(15) NULL,
  `src_port` INT NULL,
  `dst_ip` VARCHAR(15) NULL,
  `event_type` VARCHAR(45) NULL,
  `data_type` VARCHAR(45) NULL,
  `request` LONGTEXT NULL,
  `id` VARCHAR(45) NULL,
  `response` LONGTEXT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
