-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 10:42:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Dionaea
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Dionaea` ;

-- -----------------------------------------------------
-- Schema Dionaea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Dionaea` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Honeypot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Honeypot` ;

-- -----------------------------------------------------
-- Schema Honeypot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Honeypot` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema glastopf
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `glastopf` ;

-- -----------------------------------------------------
-- Schema glastopf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `glastopf` DEFAULT CHARACTER SET utf8 ;
USE `Dionaea` ;

-- -----------------------------------------------------
-- Table `Dionaea`.`connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`connections` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`connections` (
  `connection` INT(11) NOT NULL AUTO_INCREMENT,
  `connection_type` VARCHAR(45) NULL DEFAULT NULL,
  `connection_transport` VARCHAR(45) NULL DEFAULT NULL,
  `connection_protocol` VARCHAR(45) NULL DEFAULT NULL,
  `connection_timestamp` INT(11) NULL DEFAULT NULL,
  `connection_root` INT(11) NULL DEFAULT NULL,
  `local_host` VARCHAR(45) NULL DEFAULT NULL,
  `local_port` INT(11) NULL DEFAULT NULL,
  `remote_host` VARCHAR(45) NULL DEFAULT NULL,
  `remote_hostname` TINYTEXT NULL DEFAULT NULL,
  `remote_port` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`connection`),
  INDEX `connections_type_idx` (`connection_type` ASC),
  INDEX `connections_timestamp_idx` (`connection_timestamp` ASC),
  INDEX `connections_root_idx` (`connection_root` ASC),
  INDEX `connections_local_host_idx` (`local_host` ASC),
  INDEX `connections_local_port_idx` (`local_port` ASC),
  INDEX `connections_remote_host_idx` (`remote_host` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`dcerpcbinds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`dcerpcbinds` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`dcerpcbinds` (
  `dcerpcbind` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `dcerpcbind_uuid` LONGTEXT NULL DEFAULT NULL,
  `dcerpcbind_transfersyntax` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`dcerpcbind`),
  INDEX `dcerpcbinds_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`dcerpcrequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`dcerpcrequests` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`dcerpcrequests` (
  `dcerpcrequest` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `dcerpcrequest_uuid` LONGTEXT NULL DEFAULT NULL,
  `dcerpcrequest_opnum` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`dcerpcrequest`),
  INDEX `dcerpcrequests_opnum_idx` (`dcerpcrequest_opnum` ASC),
  INDEX `dcerpcrequests_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`dcerpcserviceops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`dcerpcserviceops` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`dcerpcserviceops` (
  `dcerpcserviceop` INT(11) NOT NULL AUTO_INCREMENT,
  `dcerpcservice` INT(11) NULL DEFAULT NULL,
  `dcerpcserviceop_opnum` INT(11) NULL DEFAULT NULL,
  `dcerpcserviceop_name` TINYTEXT NULL DEFAULT NULL,
  `dcerpcserviceop_vuln` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`dcerpcserviceop`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`dcerpcservices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`dcerpcservices` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`dcerpcservices` (
  `dcerpcservice` INT(11) NOT NULL AUTO_INCREMENT,
  `dcerpcservice_uuid` LONGTEXT NULL DEFAULT NULL,
  `dcerpcservice_name` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`dcerpcservice`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`downloads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`downloads` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`downloads` (
  `download` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `download_url` LONGTEXT NULL DEFAULT NULL,
  `download_md5_hash` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`download`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`emu_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`emu_profiles` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`emu_profiles` (
  `emu_profile` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `emu_profile_json` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`emu_profile`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`emu_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`emu_services` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`emu_services` (
  `emu_serivce` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `emu_service_url` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`emu_serivce`),
  INDEX `emu_services_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`logins` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`logins` (
  `login` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT NULL,
  `login_username` TINYTEXT NULL DEFAULT NULL,
  `login_password` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mqtt_fingerprints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mqtt_fingerprints` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mqtt_fingerprints` (
  `mqtt_fingerprint` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `mqtt_fingerprint_clientid` TINYTEXT NULL DEFAULT NULL,
  `mqtt_fingerprint_willtopic` LONGTEXT NULL DEFAULT NULL,
  `mqtt_fingerprint_willmessage` LONGTEXT NULL DEFAULT NULL,
  `mqtt_fingerprint_username` TINYTEXT NULL DEFAULT NULL,
  `mqtt_fingerprint_password` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`mqtt_fingerprint`),
  INDEX `mqtt_fingerprints_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mqtt_publish_commands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mqtt_publish_commands` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mqtt_publish_commands` (
  `mqtt_publish_command` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `mqtt_publish_command_topic` TINYTEXT NULL DEFAULT NULL,
  `mqtt_publish_command_message` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`mqtt_publish_command`),
  INDEX `mqtt_publish_commands_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mqtt_subscribe_commands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mqtt_subscribe_commands` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mqtt_subscribe_commands` (
  `mqtt_subscribe_command` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `mqtt_subscribe_command_messageid` TINYTEXT NULL DEFAULT NULL,
  `mqtt_subscribe_command_topic` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`mqtt_subscribe_command`),
  INDEX `mqtt_subscribe_commands_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mssql_commands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mssql_commands` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mssql_commands` (
  `mssql_command` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `mssql_command_status` TINYTEXT NULL DEFAULT NULL,
  `mssql_command_cmd` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`mssql_command`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mssql_fingerprints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mssql_fingerprints` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mssql_fingerprints` (
  `mssql_fingerprint` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `mssql_fingerprint_hostname` TINYTEXT NULL DEFAULT NULL,
  `mssql_fingerprint_appname` TINYTEXT NULL DEFAULT NULL,
  `mssql_fingerprint_cltintname` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`mssql_fingerprint`),
  INDEX `mssql_fingerprints_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mysql_command_args`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mysql_command_args` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mysql_command_args` (
  `mysql_command_arg` INT(11) NOT NULL AUTO_INCREMENT,
  `mysql_command` INT(11) NULL DEFAULT NULL,
  `mysql_command_arg_index` FLOAT NOT NULL,
  `mysql_command_arg_data` LONGTEXT NOT NULL,
  PRIMARY KEY (`mysql_command_arg`),
  INDEX `mysql_command_args_command_idx` (`mysql_command` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mysql_command_ops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mysql_command_ops` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mysql_command_ops` (
  `mysql_command_op` INT(11) NOT NULL AUTO_INCREMENT,
  `mysql_command_cmd` INT(11) NOT NULL,
  `mysql_command_op_name` TINYTEXT NOT NULL,
  PRIMARY KEY (`mysql_command_op`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`mysql_commands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`mysql_commands` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`mysql_commands` (
  `mysql_command` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `mysql_command_cmd` FLOAT NOT NULL,
  PRIMARY KEY (`mysql_command`),
  INDEX `mysql_commands_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`offers` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`offers` (
  `offer` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `offer_url` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`offer`),
  INDEX `offers_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`p0fs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`p0fs` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`p0fs` (
  `p0f` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `p0f_genre` LONGTEXT NULL DEFAULT NULL,
  `p0f_uptime` INT(11) NULL DEFAULT NULL,
  `p0f_link` TINYTEXT NULL DEFAULT NULL,
  `p0f_detail` LONGTEXT NULL DEFAULT NULL,
  `p0f_tos` TINYTEXT NULL DEFAULT NULL,
  `p0f_dist` INT(11) NULL DEFAULT NULL,
  `p0f_nat` INT(11) NULL DEFAULT NULL,
  `p0f_fw` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`p0f`),
  INDEX `p0fs_uptime_idx` (`p0f_uptime` ASC),
  INDEX `p0fs_connection_idx` (`connection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Dionaea`.`resolves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dionaea`.`resolves` ;

CREATE TABLE IF NOT EXISTS `Dionaea`.`resolves` (
  `resolve` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NULL DEFAULT NULL,
  `resolve_hostname` TINYTEXT NULL DEFAULT NULL,
  `resolve_type` TINYTEXT NULL DEFAULT NULL,
  `resolve_result` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`resolve`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `Honeypot` ;

-- -----------------------------------------------------
-- Table `Honeypot`.`Conpot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Honeypot`.`Conpot` ;

CREATE TABLE IF NOT EXISTS `Honeypot`.`Conpot` (
  `timestamp` VARCHAR(45) NOT NULL,
  `src_ip` VARCHAR(15) NULL DEFAULT NULL,
  `src_port` INT(11) NULL DEFAULT NULL,
  `dst_ip` VARCHAR(15) NULL DEFAULT NULL,
  `event_type` VARCHAR(45) NULL DEFAULT NULL,
  `data_type` VARCHAR(45) NULL DEFAULT NULL,
  `request` LONGTEXT NULL DEFAULT NULL,
  `id` VARCHAR(45) NULL DEFAULT NULL,
  `response` LONGTEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Honeypot`.`Cowrie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Honeypot`.`Cowrie` ;

CREATE TABLE IF NOT EXISTS `Honeypot`.`Cowrie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `session` VARCHAR(45) NULL DEFAULT NULL,
  `eventid` VARCHAR(45) NULL DEFAULT NULL,
  `timestamp` VARCHAR(45) NULL DEFAULT NULL,
  `message` LONGTEXT NULL DEFAULT NULL,
  `username` LONGTEXT NULL DEFAULT NULL,
  `password` LONGTEXT NULL DEFAULT NULL,
  `system` LONGTEXT NULL DEFAULT NULL,
  `src_ip` VARCHAR(45) NULL DEFAULT NULL,
  `src_port` INT(11) NULL DEFAULT NULL,
  `dst_ip` VARCHAR(45) NULL DEFAULT NULL,
  `dst_port` INT(11) NULL DEFAULT NULL,
  `input` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `session_in` (`session` ASC),
  INDEX `eventid_in` (`eventid` ASC),
  INDEX `timestamp_in` (`timestamp` ASC),
  INDEX `src_ip_in` (`src_ip` ASC),
  INDEX `src_port_in` (`src_port` ASC),
  INDEX `dst_ip_in` (`dst_ip` ASC),
  INDEX `dst_port_in` (`dst_port` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Honeypot`.`Honeytrap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Honeypot`.`Honeytrap` ;

CREATE TABLE IF NOT EXISTS `Honeypot`.`Honeytrap` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_virtual` VARCHAR(45) NULL DEFAULT NULL,
  `timestamp` VARCHAR(45) NULL DEFAULT NULL,
  `start_time` VARCHAR(45) NULL DEFAULT NULL,
  `end_time` VARCHAR(45) NULL DEFAULT NULL,
  `attack_protocol` VARCHAR(45) NULL DEFAULT NULL,
  `remote_ip` VARCHAR(45) NULL DEFAULT NULL,
  `remote_port` INT(11) NULL DEFAULT NULL,
  `local_ip` VARCHAR(45) NULL DEFAULT NULL,
  `local_port` INT(11) NULL DEFAULT NULL,
  `payload_md5` VARCHAR(45) NULL DEFAULT NULL,
  `payload_sha512` VARCHAR(128) NULL DEFAULT NULL,
  `payload_len` INT(11) NULL DEFAULT NULL,
  `payload_datahex` LONGTEXT NULL DEFAULT NULL,
  `proxy_protocol` VARCHAR(45) NULL DEFAULT NULL,
  `proxy_rmip` VARCHAR(45) NULL DEFAULT NULL,
  `proxy_rmport` INT(11) NULL DEFAULT NULL,
  `proxy_loip` VARCHAR(45) NULL DEFAULT NULL,
  `proxy_loport` INT(11) NULL DEFAULT NULL,
  `proxy_payload_md5` VARCHAR(45) NULL DEFAULT NULL,
  `proxy_payload_sha512` VARCHAR(128) NULL DEFAULT NULL,
  `proxy_payload_len` INT(11) NULL DEFAULT NULL,
  `proxy_payload_datahex` LONGTEXT NULL DEFAULT NULL,
  `operation_mode` INT(11) NULL DEFAULT NULL,
  `download_count` INT(11) NULL DEFAULT NULL,
  `download_tries` INT(11) NULL DEFAULT NULL,
  `downloads` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_idx` (`id` ASC),
  INDEX `timestamp_idx` (`timestamp` ASC),
  INDEX `start_time_idx` (`start_time` ASC),
  INDEX `end_time_idx` (`end_time` ASC),
  INDEX `attack_protocol_idx` (`attack_protocol` ASC),
  INDEX `remoteip_idx` (`remote_ip` ASC),
  INDEX `remote_port_idx` (`remote_port` ASC),
  INDEX `local_ip_idx` (`local_ip` ASC),
  INDEX `local_port_idx` (`local_port` ASC),
  INDEX `payload_md5_idx` (`payload_md5` ASC),
  INDEX `payload_md512_idx` (`payload_sha512` ASC),
  INDEX `payload_len_idx` (`payload_len` ASC),
  INDEX `proxy_protocol_idx` (`proxy_protocol` ASC),
  INDEX `proxy_rmip_idx` (`proxy_rmip` ASC),
  INDEX `proxy_rmport_idx` (`proxy_rmport` ASC),
  INDEX `proxy_loip_idx` (`proxy_loip` ASC),
  INDEX `proxy_loport_idx` (`proxy_loport` ASC),
  INDEX `proxy_payload_md5_idx` (`proxy_payload_md5` ASC),
  INDEX `proxy_payload_md512_idx` (`proxy_payload_sha512` ASC),
  INDEX `proxy_payload_len_idx` (`proxy_payload_len` ASC),
  INDEX `operation_mode_idx` (`operation_mode` ASC),
  INDEX `download_count_idx` (`download_count` ASC),
  INDEX `download_tries_idx` (`download_tries` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `glastopf` ;

-- -----------------------------------------------------
-- Table `glastopf`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`events` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(45) NULL DEFAULT NULL,
  `source` VARCHAR(45) NULL DEFAULT NULL,
  `request_url` VARCHAR(1000) NULL DEFAULT NULL,
  `request_raw` LONGTEXT NULL DEFAULT NULL,
  `pattern` VARCHAR(45) NULL DEFAULT NULL,
  `filename` VARCHAR(1000) NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `sensorid` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `glastopf`.`ext`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`ext` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`ext` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `firsttime` VARCHAR(45) NULL DEFAULT NULL,
  `lasttime` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `glastopf`.`filetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`filetype` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`filetype` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `firsttime` VARCHAR(45) NULL DEFAULT NULL,
  `lasttime` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `glastopf`.`intext`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`intext` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`intext` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `firsttime` VARCHAR(45) NULL DEFAULT NULL,
  `lasttime` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `glastopf`.`intitle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`intitle` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`intitle` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `firsttime` VARCHAR(45) NULL DEFAULT NULL,
  `lasttime` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `glastopf`.`inurl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`inurl` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`inurl` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `firsttime` VARCHAR(45) NULL DEFAULT NULL,
  `lasttime` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `glastopf`.`ip_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`ip_profiles` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`ip_profiles` (
  `ip` VARCHAR(15) NOT NULL,
  `as_number` VARCHAR(10) NULL DEFAULT NULL,
  `as_name` VARCHAR(120) NULL DEFAULT NULL,
  `country_code` VARCHAR(10) NULL DEFAULT NULL,
  `total_requests` INT(11) NULL DEFAULT NULL,
  `total_scans` INT(11) NULL DEFAULT NULL,
  `bgp_prefix` VARCHAR(100) NULL DEFAULT NULL,
  `requests_per_scan` FLOAT NULL DEFAULT NULL,
  `avg_scan_duration` FLOAT NULL DEFAULT NULL,
  `scan_time_period` FLOAT NULL DEFAULT NULL,
  `last_event_time` VARCHAR(30) NULL DEFAULT NULL,
  `comments` LONGTEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `glastopf`.`allinurl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glastopf`.`allinurl` ;

CREATE TABLE IF NOT EXISTS `glastopf`.`allinurl` (
  `content` VARCHAR(200) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `firsttime` VARCHAR(45) NULL DEFAULT NULL,
  `lasttime` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `Dionaea`;

DELIMITER $$

USE `Dionaea`$$
DROP TRIGGER IF EXISTS `Dionaea`.`connections_AFTER_INSERT` $$
USE `Dionaea`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `Dionaea`.`connections_AFTER_INSERT`
AFTER INSERT ON `Dionaea`.`connections`
FOR EACH ROW
while new.connection_root is null
do
UPDATE connections SET connection_root = connection WHERE connection = new.connection AND new.connection_root IS NULL;
END while$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
